spark_master: "spark://spark-network:7077"
spark_app_name: "MySparkApp"
spark_executor_memory: "2g"
spark_executor_cores: 2
spark_num_executors: 2
spark_driver_memory: "1g"
spark_driver_cores: 1
spark_sql_shuffle_partitions: 200
spark_default_parallelism: 200
spark_log_level: "WARN"
spark_volume_mount_data_path: "/usr/src/app/parquet_folder"